### ISSUE TITLE
Error when dependency lacks version (legacy Projectfile)

### ISSUE THREAD

**Issue by luislavena** [ysbaddaden/shards#52]
Hello,

Testing against latest master, Shards fails to parse `Projectfile` as legacy.

Example:

```yaml
name: testing
version: 0.0.1

dependencies:
  routing:
    github: bcardiff/crystal-routing
    branch: master
```

Results in the following output:

```
in shard.yml:1: Shards::ParseError: missing required attribute: version at 1:0

  1. name: routing
     ^
```

In this particular case I believe the issue is introduced by the lack of version tags in the dependency repository, but not sure.

Thank you.
