### ISSUE TITLE
Shards installs wrong version of lucky

### ISSUE THREAD

**Issue by robacarp** [ysbaddaden/shards#562]
With this shard file, I expect it to install lucky [1.0.0-rc1](https://github.com/luckyframework/lucky/releases/tag/v1.0.0-rc1). That tag appears correct, and the version number in the shard.yml for the project is correct as well.

However, what it installs is v0.30.1 instead. Nothing I do can make it install correctly. With the shard file shared around, others are able to see the behavior as well.

This does not happen with shards 0.17.0 and crystal 1.5.1, but it happens reliably with crystal 1.6.0 and shards 0.17.1.

```
name: app
version: 0.1.0

crystal: 1.6.0

dependencies:
  lucky:
    github: luckyframework/lucky
    version: ~> 1.0.0-rc1 # branch: master
```

To clarify, the _output_ of the shard command indicates that it understands the assignment and thinks it's doing the right thing, but what lands is incorrect:

```
$ shards install -v
Resolving dependencies
git ls-remote --get-url origin
Fetching https://github.com/luckyframework/lucky.git
git fetch --all --quiet
git ls-tree -r --full-tree --name-only refs/tags/v1.0.0-rc1 -- shard.yml
git show refs/tags/v1.0.0-rc1:shard.yml
...
```

```
$ cat lib/lucky/shard.yml | grep version | head -n 1
version: 0.30.1
```

Shards 0.17.1 (2022-09-30)
MacOS
