### ISSUE TITLE
branch master not satisfy condition >=

### ISSUE THREAD

**Issue by kostya** [ysbaddaden/shards#563]
My project have dependencies (master because i want to test some things, before release version):
`shard1`
`shard2 branch: master`

shard1 have dependencies:
`shard2 version >= '1.0.0'`

both dependencies is ok, because master is >= 1.0.0, but shards unable to resolve this `Failed to resolve dependencies`.

**Comment by straight-shoota** [comment]
Can you provide a reproducible example?
This should be expected to work, as you mention. And I'm sure `shards` does that correctly (in general).

**Comment by kostya** [comment]
```
dependencies:
  test_shard1:
    github: kostya/test_shard1
  test_shard2:
    github: kostya/test_shard2
    branch: master
```

shards --version
Shards 0.17.0 [85b30b5] (2022-03-24)

```
shards update
Resolving dependencies
Fetching https://github.com/kostya/test_shard1.git
Fetching https://github.com/kostya/test_shard2.git
Unable to satisfy the following requirements:

- `test_shard2 (branch master)` required by `shard.yml`
- `test_shard2 (>= 1.0.0)` required by `test_shard1 0.1.0`
Failed to resolve dependencies


```
