### ISSUE TITLE
Shards cannot create shard.lock

### ISSUE THREAD

**Issue by sdogruyol** [ysbaddaden/shards#71]
If a project has no release tags in Github shards cannot create shard.lock that's why you cant use it in your app. In this case https://github.com/ysbaddaden/artanis has no release tags

This fails

```yml
dependencies:
  artanis:
    github: ysbaddaden/artanis
```

Meanwhile this works

```yml
dependencies:
  artanis:
    github: ysbaddaden/artanis
    commit: HEAD
```

**Comment by jhass** [comment]
`branch: master` should work too. I believe this is intended and merely missing validation.

**Comment by ysbaddaden** [comment]
Not exactly. When nothing is specified, the Git resolver defaults to `version: *`. If the dependency didn't make release, it defaults to installing the current `HEAD`. It works, but the generated `shard.lock` is faulty:

```yaml
version: 1.0
shards:
  artanis:
    github: ysbaddaden/artanis
    version: HEAD
```

Obviously this should be `commit: <sha1>`.
