### ISSUE TITLE
possible recursion

### ISSUE THREAD

**Issue by kostya** [ysbaddaden/shards#72]
i have typo and write:

```yaml
dependencies:
  cron_parser:
    github: kostya/cron_scheduler
```

shards command hangs forever.
then i fix it with change cron_parser -> cron_scheduler.
