### ISSUE TITLE
Short notation?

### ISSUE THREAD

**Issue by kostya** [ysbaddaden/shards#75]
```
 dependencies:
   cron_scheduler:
     github: kostya/cron_scheduler
   nagios_check:
     github: kostya/nagios_check
   pg:
     github: will/crystal-pg
  redis:
    github: stefanwille/crystal-redis
```
this is too noisy to manual edit, repeated some parts

why not add default short notation together with full notation, which will be used in most cases:

`[git|github|bitbucket|path]:user/repo[#version|branch|tag][@revision]`

```
 dependencies:
   - github:kostya/cron_scheduler@bde084a30
```

or even group by github:

```
 dependencies:
   github:
     - kostya/cron_scheduler
     - kostya/nagios_check
     - will/crystal-pg
     - stefanwille/crystal-redis
```
