### ISSUE TITLE
Feature request: Hooks 

### ISSUE THREAD

**Issue by marceloboeira** [ysbaddaden/shards#88]
Currently, as far as I know, shards install process only clones the repository inside the `libs` folder, yet, I want run something before or after the process has finished, in order to install for instance a external dependency, or anything that comes to mind.

Purpose example, on the some libs `shards.yml` file:
```yaml
name: shards
version: 0.6.0
...
hooks: 
  before_install: hooks/before_install
  after_install: hooks/after_install
```
That could even be implicit, if there is a hooks folder with before_install/after_install files... but anyway what do you guys think about it?
